### ISSUE TITLE
Možnost nastavení jednotky (ks, h, kg)

### ISSUE THREAD

**Issue by ghost** [obrejla/Eciovni#7]
Chybí mi možnost nastavení jednotky (ks, h, kg). Mohl bys to prosím přidat?

**Comment by janbarasek** [comment]
@JakubKontra Pošli prosím PR, díky.

**Comment by janbarasek** [comment]
Implementováno. https://github.com/obrejla/Eciovni/commit/fcf94d177ac8db7b424a97be3c358e1ed0d81ac6

Bez jednotky (defaultní chování):

![Snímek obrazovky 2020-08-06 v 15 35 27](https://user-images.githubusercontent.com/4738758/89538118-74d2f680-d7fa-11ea-9f17-025e75a73b22.png)

S jednotkou:

Nastavuje se jako `$invoice->setUnit('hod');`:

![Snímek obrazovky 2020-08-06 v 15 36 14](https://user-images.githubusercontent.com/4738758/89538207-916f2e80-d7fa-11ea-911e-4c1cd55b2c0e.png)
